const copypastas = [
    "Hey you stupid fucking mathematician cunts would it fucking kill you to write out a goddamn sentence, with actual fucking words, once in a while explaining what the fuck it even is that you just fucking did or what the fuck I'm supposed to actually do with your stupid fucking abstract mathematical objects? I know you have some sick fetish/obsession with trying to explain everything with just numbers and symbols and using the least amount of words possible because you were probably such a fucking socially awkward weirdo your whole life that now you need to try and prove you're better than anyone at all making your fucking ideas unnecessarily obtuse and inaccessible to anyone but your snide little mathematician friends, but the only reason we keep you on the payroll is to come up with tools for us to use to solve real problems. Sure we let you dick around with your insanely nonsensical 97 dimensional semicuspidal manifolds or your hyperbolic triangles without embedded eigenvalues or whatever the fuck it is you assholes are doing all day. But that's just to keep you little shits busy so you don't bother the rest of us with your fucking bullshit periodic approximations of irrational pseudo-rotations using pseudoholomorphic curves. Jesus Fucking Christ. All I'm asking for is ONE (maybe 2) sentences explaining what the fuck this shit even represents. You can blame it on me. Tell your math buddies I snuck it and wrote 'words' while you weren't looking. Just please, for the love of god, tell the rest of us what you are doing and what you want us to do.",

    "in the stripped club. straight up \"jorking it\". and by \"it\", haha, well. let's justr say. My peanits",

    "Connection terminated. I'm sorry to interrupt you, Elizabeth, if you still even remember that name, But I'm afraid you've been misinformed. You are not here to receive a gift, nor have you been called here by the individual you assume, although, you have indeed been called. You have all been called here, into a labyrinth of sounds and smells, misdirection and misfortune. A labyrinth with no exit, a maze with no prize. You don't even realize that you are trapped. Your lust for blood has driven you in endless circles, chasing the cries of children in some unseen chamber, always seeming so near, yet somehow out of reach, but you will never find them. None of you will. This is where your story ends.<br><br>And to you, my brave volunteer, who somehow found this job listing not intended for you, although there was a way out planned for you, I have a feeling that's not what you want. I have a feeling that you are right where you want to be. I am remaining as well. I am nearby. This place will not be remembered, and the memory of everything that started this can finally begin to fade away. As the agony of every tragedy should.<br><br>And to you monsters trapped in the corridors, be still and give up your spirits. They don't belong to you. For most of you, I believe there is peace and perhaps more waiting for you after the smoke clears. Although, for one of you, the darkest pit of Hell has opened to swallow you whole, so don't keep the devil waiting, old friend.<br><br>My daughter, if you can hear me, I knew you would return as well. It's in your nature to protect the innocent. I'm sorry that on that day, the day you were shut out and left to die, no one was there to lift you up into their arms the way you lifted others into yours, and then, what became of you. I should have known you wouldn't be content to disappear, not my daughter. I couldn't save you then, so let me save you now. It's time to rest - for you, and for those you have carried in your arms.<br><br>This ends for all of us.<br><br>End communication.",

    "Reddit, am I the arsehole? My mum (82F) told me (12M) to do the dishes (16) but I (12M) was too busy playing Fortnite (3 kills) so I (12M) grabbed my controller (DualShock 4) and threw it at her (138kph). She fucking died, and I (12M) went to prison (18 years). While in prison I (12M) incited several riots (3) and assumed leadership of a gang responsible for smuggling drugs (cocaine) into the country. I (12M) also ordered the assassination of several celebrities (Michael Jackson, Elvis Presley and Jeffrey Epstein) and planned a terrorist attack (9/11). Reddit, AITA?"
];

const elem = document.getElementById("copypasta");

function updateCopypasta() {
    elem.innerHTML = copypastas[Math.floor(Math.random() * copypastas.length)]
}

updateCopypasta();
